# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOOSE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOOSE_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGOOSE_DATABASE}
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGOOSE_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGOOSE_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGOOSE_USER}:${MONGOOSE_PASSWORD}@mongo:27017/